// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BTDToolbox.Classes.JSON_Classes;
//
//    var towerSpriteUpgrade = TowerSpriteUpgrade.FromJson(jsonString);

namespace BTDToolbox.Classes.JSON_Classes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TowerSpriteUpgrade
    {
        [JsonProperty("Sprites")]
        public Dictionary<string, string> Sprites { get; set; }

        [JsonProperty("UpgradeLevels")]
        public Dictionary<string, long> UpgradeLevels { get; set; }
    }

    public partial class TowerSpriteUpgrade
    {
        public static TowerSpriteUpgrade FromJson(string json) => JsonConvert.DeserializeObject<TowerSpriteUpgrade>(json, BTDToolbox.Classes.JSON_Classes.Converter.Settings);
    }
}
