// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do one of these:
//
//    using QuickType;
//
//    var artist = Artist.FromJson(jsonString);
//    var album = Album.FromJson(jsonString);
//    var track = Track.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Album
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("artist")]
        public ArtistClass Artist { get; set; }

        [JsonProperty("tracks")]
        public Track[] Tracks { get; set; }
    }

    public partial class ArtistClass
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("founded")]
        public long Founded { get; set; }

        [JsonProperty("members")]
        public string[] Members { get; set; }
    }

    public partial class Track
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }
    }

    public partial class Artist
    {
        public static Artist FromJson(string json) => JsonConvert.DeserializeObject<Artist>(json, QuickType.Converter.Settings);
    }

    public partial class Album
    {
        public static Album FromJson(string json) => JsonConvert.DeserializeObject<Album>(json, QuickType.Converter.Settings);
    }

    public partial class Track
    {
        public static Track FromJson(string json) => JsonConvert.DeserializeObject<Track>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Artist self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
        public static string ToJson(this Album self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
        public static string ToJson(this Track self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
